add input inputs autocomplete, id and name
PrefectHQ/miter-design pull request #174
Opened 2022-02-06 17:42 UTC by zhen0

## PR Checklist

(_all items must be checked off for a PR to be merged_)

This PR:

- [ ] has a changelog entry with a short description of what's changed in `CHANGELOG.md`
- [ ] adds new tests or updates existing tests (or hasn't, for reasons explained below)
- [ ] strictly follows the design spec (if one exists)
- [ ] adheres to [a11y guidelines](https://www.a11yproject.com/checklist/)/[WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) guidelines where applicable; this can be tested using Lighthouse (native in Chrome dev tools or as a plugin for other browsers) and with accessibility reports in Firefox

This PR has been tested in the following browsers (the latest version of each is fine):

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

## PR description

2022-02-07 15:44 UTC, znicholasbrown requested changes
I'm fine with adding these like this, though as @pleek91 mentioned in #173 it might make more sense to fully pass `$attrs` to the input node. Given that there are a bunch of props that are used for periphery options this might not make sense without a refactor but I'll defer to @pleek91 here

2022-02-07 15:44 UTC, znicholasbrown commented on src/components/Input/Input.vue
> +      type: Boolean,
This should be `type: string`; https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2022-02-07 15:51 UTC, pleek91 commented
@zhen0 @znicholasbrown I'm okay with adding these now for speed if needed but using `$attrs` is definitely the way to go. Otherwise we'll be back adding more attributes next time we need a different one

2022-02-07 16:00 UTC, zhen0 commented
> @zhen0 @znicholasbrown I'm okay with adding these now for speed if needed but using `$attrs` is definitely the way to go. Otherwise we'll be back adding more attributes next time we need a different one

I hadn't seen the suggestion in #173 but it definitely makes more sense.

2022-02-08 16:42 UTC, pleek91 requested changes

2022-02-08 16:42 UTC, pleek91 commented on src/components/Input/Input.vue
> +    },
```suggestion
    outerClassList(): any {
      return [
        ...this.$attrs.class,
        {
          disabled: this.disabled,
          invalid: this.invalid,
          active: this.active,
          hovered: this.hovered
        }
      ]
    },
```

2022-02-08 16:42 UTC, pleek91 commented on src/components/Input/Input.vue
> +      const { ...attrs } = this.$attrs
We need to remove `class` and `style` from `$attrs` so they don't get bound to the input.  
```suggestion
      const { class, style, ...attrs } = this.$attrs
```

2022-02-08 16:48 UTC, pleek91 commented on src/components/Input/Input.vue
> +    },
Realizing the logic here might not be quite right. The original will bind `disabled` but not `invalid` if you pass in both props. Which seems odd to me 🤔

2022-02-08 18:54 UTC, pleek91 approved these changes
LGTM!

2022-02-08 22:51 UTC, znicholasbrown approved these changes

2022-02-09 21:18 UTC, merged